1

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -47,77 +47,77 @@ jobs:
         path: src/TodoWebapp/publish
 
 
-  provision-api:
-    runs-on: ubuntu-latest
-    needs: build
-    permissions:
-      id-token: write
-      contents: read
-      checks: write
-      issues: write
-    env: # these variables will be set as environment variables for script actions and are needed to run Terraform commands
-      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
-      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
-      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
-      ARM_USE_OIDC: true # to use OIDC authentication on Terraform
-      ARTIFACT_NAME: todo-api
-    defaults:
-      run:
-        working-directory: ./deploy/terraform/todo-api
+  # provision-api:
+  #   runs-on: ubuntu-latest
+  #   needs: build
+  #   permissions:
+  #     id-token: write
+  #     contents: read
+  #     checks: write
+  #     issues: write
+  #   env: # these variables will be set as environment variables for script actions and are needed to run Terraform commands
+  #     ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
+  #     ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+  #     ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
+  #     ARM_USE_OIDC: true # to use OIDC authentication on Terraform
+  #     ARTIFACT_NAME: todo-api
+  #   defaults:
+  #     run:
+  #       working-directory: ./deploy/terraform/todo-api
 
-    steps:
-    - uses: actions/checkout@v3
+  #   steps:
+  #   - uses: actions/checkout@v3
 
-    - uses: actions/download-artifact@v4
-      with:
-        name: ${{ env.ARTIFACT_NAME }}
-        path: ./${{ env.ARTIFACT_NAME }}
+  #   - uses: actions/download-artifact@v4
+  #     with:
+  #       name: ${{ env.ARTIFACT_NAME }}
+  #       path: ./${{ env.ARTIFACT_NAME }}
     
-    - uses: azure/login@v1
-      with:
-        client-id: ${{ secrets.AZURE_CLIENT_ID }}
-        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
-        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+  #   - uses: azure/login@v1
+  #     with:
+  #       client-id: ${{ secrets.AZURE_CLIENT_ID }}
+  #       tenant-id: ${{ secrets.AZURE_TENANT_ID }}
+  #       subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
     
-    - uses: hashicorp/setup-terraform@v2
-      with:
-        terraform_wrapper: false
+  #   - uses: hashicorp/setup-terraform@v2
+  #     with:
+  #       terraform_wrapper: false
 
-    - name: terraform init
-      run: terraform init
+  #   - name: terraform init
+  #     run: terraform init
     
-    - name: terraform plan
-      id: tfplan
-      run: terraform plan -var="dbPassword=${{ secrets.DB_PASSWORD }}" -var="env=prod" -out=tfplan
+  #   - name: terraform plan
+  #     id: tfplan
+  #     run: terraform plan -var="dbPassword=${{ secrets.DB_PASSWORD }}" -var="env=prod" -out=tfplan
 
-    - name: Terraform Plan Status
-      if: steps.tfplan.outcome == 'failure'
-      run: exit 1
+  #   - name: Terraform Plan Status
+  #     if: steps.tfplan.outcome == 'failure'
+  #     run: exit 1
 
-    - name: terraform apply
-      run: |
-        terraform apply tfplan
-        echo "WEBAPP_NAME=$(terraform output -raw webappName)" >> $GITHUB_ENV
-        echo "DB_ADDRESS=$(terraform output -raw dbAddress)" >> $GITHUB_ENV
-        echo "WEBAPP_URL=$(terraform output -raw webappUrl)" >> $GITHUB_ENV
+  #   - name: terraform apply
+  #     run: |
+  #       terraform apply tfplan
+  #       echo "WEBAPP_NAME=$(terraform output -raw webappName)" >> $GITHUB_ENV
+  #       echo "DB_ADDRESS=$(terraform output -raw dbAddress)" >> $GITHUB_ENV
+  #       echo "WEBAPP_URL=$(terraform output -raw webappUrl)" >> $GITHUB_ENV
 
-    - name: 'Azure webapp deploy - Prod'
-      id: prod-deploy
-      uses: azure/webapps-deploy@v2
-      with: 
-        app-name: ${{ env.WEBAPP_NAME }}
-        package: ./${{ env.ARTIFACT_NAME }}
+  #   - name: 'Azure webapp deploy - Prod'
+  #     id: prod-deploy
+  #     uses: azure/webapps-deploy@v2
+  #     with: 
+  #       app-name: ${{ env.WEBAPP_NAME }}
+  #       package: ./${{ env.ARTIFACT_NAME }}
 
-    - name: 'Configure azure webapp - Prod'
-      uses: azure/appservice-settings@v1
-      with:
-        app-name: ${{ env.WEBAPP_NAME }}
-        mask-inputs: false
-        app-settings-json: '[{"name": "ConnectionStrings__TodosDb","value": "Server=${{ env.DB_ADDRESS }};Database=TodoDB;Port=5432;User Id=dbadmin;Password=${{ secrets.DB_PASSWORD }};Ssl Mode=VerifyFull;","slotSetting": true}, {"name": "ASPNETCORE_ENVIRONMENT", "value": "Development"}]'
+  #   - name: 'Configure azure webapp - Prod'
+  #     uses: azure/appservice-settings@v1
+  #     with:
+  #       app-name: ${{ env.WEBAPP_NAME }}
+  #       mask-inputs: false
+  #       app-settings-json: '[{"name": "ConnectionStrings__TodosDb","value": "Server=${{ env.DB_ADDRESS }};Database=TodoDB;Port=5432;User Id=dbadmin;Password=${{ secrets.DB_PASSWORD }};Ssl Mode=VerifyFull;","slotSetting": true}, {"name": "ASPNETCORE_ENVIRONMENT", "value": "Development"}]'
 
-    - name: logout
-      run: |
-        az logout
+  #   - name: logout
+  #     run: |
+  #       az logout
 
 
   provision-webapp:
@@ -200,7 +200,7 @@ jobs:
 
   prod-dast:
     runs-on: ubuntu-latest
-    needs: [provision-api, provision-webapp]
+    needs: [provision-webapp]
     env:
       WEBAPP_URL: ${{needs.provision-webapp.outputs.webappUrl}}
     permissions:
